trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install pandas matplotlib
  displayName: 'Install dependencies'

- script: |
    python src/contact_trend_analyzer.py
  displayName: 'Run analysis script'
